/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: TiBot
//
// PLATFORM:     Microchip C18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                5   // Number of tasks that can be active at one time


//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_ALL               // Enable all services: CSems, QMsg, QSmsg, TTimers, DTimers


//------------------------------------------------------------------------------
// INTERRUPT SERVICES
//------------------------------------------------------------------------------

#define OS_ENABLE_INT_CSEM
#define OS_ENABLE_INT_QMSG         // Enable services for work with queues within interrupts
#define OS_ENABLE_INT_FLAG         // Enable services for work with flags within interrupts
#define OS_ENABLE_INT_MSG          // Enable services for work with pointers to messages within interrupts
#define OS_ENABLE_INT_SMSG         // Enable services for work with simple messages within interrupts


//------------------------------------------------------------------------------
// BSEMS
//------------------------------------------------------------------------------

#define OS_BSEMS                2   // Number of binary semaphores

enum OSA_BSEMS_ENUM
{
    Mutex,                 // do or dont
    Lock 				   // Lock
};




#endif
