////////////////////////////////////////////////////////////////////////////////
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: Running lights
// PLATFORM: HT-PICC 14-bit
//
////////////////////////////////////////////////////////////////////////////////


#ifndef _OSACFG_H
#define _OSACFG_H



#define OS_TASKS               3
#define OS_DISABLE_PRIORITY
#define OS_ENABLE_TTIMERS



#endif
