/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: Tutor 5. Extended priority mode
//
// PLATFORM:     HT-PICC 14-bit
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                4   // Number of tasks that can be active at one time
#define OS_PRIORITY_LEVEL  OS_PRIORITY_EXTENDED 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)


//------------------------------------------------------------------------------
// BSEMS
//------------------------------------------------------------------------------

#define OS_BSEMS                1   // Number of binary semaphores

enum OSA_BSEMS_ENUM
{
    BS_SIGNAL                  // Запуск задач
};




#endif
